### PR TITLE
FIX: add redirect logic to return to home screen after account deleti…

### LINKED ISSUE #1: MOD: Redirect to Home Screen After Account Deletion Instead of Closing the Program
## Description
- Redirect to Home Screen After Account Deletion Instead of Closing the Program

## To do

- [x] Redirect to Home Screen After Account Deletion Instead of Closing the Program

### PR DESCRIPTION
**Pull request by yeniNcoco**
## description
- add redirect logic to return to the home screen after account deletion

## discussion point 
- I need to consider how to refactor the code to be concise without using the goto statement.
---
- close #1

### CODE REVIEW

File: App/client/client-main/chatservice-client-main/chatservice-client-main/main.cpp [hunk 1]
```diff
@@ -1113,7 +1114,7 @@ int main() {
                     userManager.modifyPw();
                     continue;
                 case '2':
-                    if (userManager.deleteUser() == 1) return -1;
+                    if (userManager.deleteUser() == 1) goto initialize;
```
Comment (yeniNcoco) [inline App/client/client-main/chatservice-client-main/chatservice-client-main/main.cpp:1117]: I want to delete this `goto` statement
